// Generated by CoffeeScript 1.9.3
(function() {
  var DEFAULTS, TRANS, addStack, css, distance, doc, later, margin, merge, notr, oneTrans, sel, stacks, styles,
    slice = [].slice;

  merge = function() {
    var i, k, len, o, os, t, v;
    t = arguments[0], os = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    for (i = 0, len = os.length; i < len; i++) {
      o = os[i];
      for (k in o) {
        v = o[k];
        if (v !== void 0) {
          t[k] = v;
        }
      }
    }
    return t;
  };

  doc = document;

  sel = function(s) {
    return doc.querySelector(s);
  };

  distance = function(el) {
    return el.offsetTop + (el.offsetParent ? distance(el.offsetParent) : 0);
  };

  later = function(f) {
    return setTimeout(f, 1);
  };

  styles = ".notr {\n    min-width: 270px;\n    min-height: 20px;\n    margin-bottom: 3px;\n    margin-top: 0;\n    float: left;\n    clear: both;\n    opacity: 1.0;\n    box-shadow: 0 0 5px rgba(0,0,0,0.5);\n    transition: margin-top 0.2s, opacity 0.2s;\n    cursor: pointer;\n}\n.notrcont {\n    position: fixed;\n    min-width: 270px;\n    min-height: 10px;\n    z-index: 9000;\n}";

  css = doc.createElement('style');

  css.type = 'text/css';

  css.innerHTML = styles;

  doc.head.appendChild(css);

  stacks = {};

  addStack = function(name, styles) {
    var el;
    if (stacks[name]) {
      return;
    }
    stacks[name] = {
      container: el = doc.createElement('div')
    };
    el.className = "notrcont notrcont-" + name;
    return merge(el.style, styles != null ? styles : {});
  };

  DEFAULTS = {
    html: 'Oh, why hallow thar!',
    className: 'alert alert-info',
    stack: 'def',
    stackStyles: {
      top: '65px',
      right: '15px'
    },
    parent: 'body',
    stay: 4000
  };

  addStack('def', DEFAULTS.stackStyles);

  margin = function(el, parent) {
    var dist, height;
    if (parent) {
      parent.appendChild(el);
    }
    dist = distance(el);
    height = el.offsetHeight;
    if (parent) {
      parent.removeChild(el);
    }
    return -1 * (height + dist);
  };

  TRANS = 'transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd'.split(' ');

  oneTrans = function(el, fn) {
    var cb, remove;
    cb = function(ev) {
      remove();
      return fn(ev);
    };
    remove = function() {
      return TRANS.forEach(function(t) {
        return el.removeEventListener(t, cb);
      });
    };
    return TRANS.forEach(function(t) {
      return el.addEventListener(t, cb);
    });
  };

  notr = function(opts) {
    var div, parent, remove, removeStackIfEmpty, stack, timeout;
    if (opts == null) {
      opts = {};
    }
    if (typeof opts === 'string') {
      opts = {
        html: opts
      };
    }
    opts = merge({}, DEFAULTS, opts);
    div = doc.createElement('div');
    div.innerHTML = opts.html;
    div.className = "notr " + opts.className;
    addStack(opts.stack, opts.stackStyles);
    stack = stacks[opts.stack];
    parent = typeof opts.parent === 'string' ? sel(opts.parent) : opts.parent;
    if (parent != null) {
      parent.appendChild(stack.container);
    }
    div.style.opacity = 0;
    div.style.marginTop = (margin(div, stack.container)) + "px";
    stack.container.appendChild(div);
    removeStackIfEmpty = function() {
      var ref;
      if (stack.container.childNodes.length !== 0) {
        return;
      }
      return (ref = stack.container.parentNode) != null ? ref.removeChild(stack.container) : void 0;
    };
    timeout = null;
    remove = function() {
      if (timeout) {
        clearTimeout(timeout);
      }
      div.style.opacity = 0;
      div.style.marginTop = (margin(div)) + "px";
      return oneTrans(div, function() {
        div.parentNode.removeChild(div);
        return removeStackIfEmpty();
      });
    };
    div.onclick = remove;
    later(function() {
      div.style.marginTop = 0;
      div.style.opacity = null;
      if (opts.stay) {
        return oneTrans(div, (function() {
          return timeout = setTimeout(remove, opts.stay);
        }));
      }
    });
    return void 0;
  };

  if (typeof module === 'object') {
    module.exports = notr;
  } else if (typeof define === 'function' && define.amd) {
    define(function() {
      return notr;
    });
  } else {
    this.notr = notr;
  }

}).call(this);

//# sourceMappingURL=notr.js.map
